##
# Ansible playbook for setting up a new drupal project

---
- hosts: vagrant
  user: vagrant
  sudo: yes

  vars_prompt:
    project: "Drupal project name"

  vars_files:
    - settings.yml

  tasks:

    - name: Apache | Add vhost for the project
      template: src=templates/etc-apache2-sites-available-devserver.j2 dest=/etc/apache2/sites-available/{{ project }}

    #- name: Mysql | Create new database
    #  mysql_db: db={{ project }} state=present

    #- name: Drush | Download and install drupal 7
    #  action: shell drush qd {{ project }} {{ modules }} -y --enable --account-mail={{ account_mail }} --account-name={{ account_name }} --account-pass={{ account_pass }} --site-name={{ site_name }} --locale={{ locale }} --db-url={{ db_url }} -y chdir=/vagrant
    #  ignore_errors: yes

    - name: Shell | Link drupal directory name to www
      command: ln -s /vagrant/{{ project }}/docroot /vagrant/{{ project }}/www

    - name: Drush | Run site install
      shell: drush -y si --db-url=mysql://root:password@localhost/{{ project }} chdir=/vagrant/{{ project }}/www
      register: siout

    - debug: siout.stdout_lines

    - name: Drush | Sync db
      shell: drush sql-sync @{{ project }}.prod @self chdir=/vagrant/{{ project }}/www
    # - name: Drush | Set aliases.drushrc.php
    #   template: src=files/drush-aliases-drushrc-php.j2 dest=/home/vagrant/.drush/{{ project }}.aliases.drushrc.php
    #
    # - name: Drush | Creates directory for sql-dump
    #   files: path=/vagrant/{{ project }}/sql-dump state=directory

    - name: Apache | Enable new project site
      shell: a2ensite {{ project }}
      notify:
        - Restart apache

  ##
  # Include handlers
  #
  handlers:
    - include: handlers.yml
